Traceback (most recent call last):
  File "<ipython-input-20-9939a9c2ce64>", line 4, in <module>
    raise Exception('this is the error message.')
Exception: this is the error message.
